favicon = "/images/130299538_10219977241674027_5939431453591207282_n.jpg"
logo = "/images/logo.png"
logo_white = "/images/logo-white.png"
logo_width = "180"
sticky_menu = false
author = "BKPA"
copyright = "Developed by [Mehedi](https://mehedisharif.com/)"
description = "Bangladesh Kidney Patient Association (BKPA)"

[preloader]
enable = true
preloader = ""
